Assignment:

---



---

Question 1-->>
From the above array, retrieve the values([[3,4],[5,6]]) using indexing

In [2]:
import numpy as np

In [3]:
list1=[1,2,3,4,5]
list2=[2,3,4,5,6]
list3=[4,5,6,7,8]

arr1=np.array([list1,list2,list3])
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8]])

In [6]:
arr1[1:3,1:3]

array([[3, 4],
       [5, 6]])

Question 2-->>Retrieve the value ([3,4,5]) using indexing.

In [7]:
arr1[1:2,1:4]

array([[3, 4, 5]])